@startuml
'https://plantuml.com/class-diagram

class Main
interface Print {
    --
    printWeak
    printStrong
}

class PrintBanner {
}

class Banner {
    --
    showWithParen
    showWithAster
}

Main --> Print : uses >
PrintBanner ..> Print
PrintBanner --|> Banner



@enduml