DROP TABLE IF EXISTS account CASCADE;

CREATE TABLE IF NOT EXISTS account (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    passphrase VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    admin_flag BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
);

